version: "3.8"

services:
  bonded-site:
    build: .
    container_name: bonded_site
    restart: unless-stopped
    networks:
      shared-services:
        ipv4_address: 172.25.0.3
    ports:
      - "8081:80"

networks:
  shared-services:
    external: true
